dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - embeddings
  corpus:
    root: my_tests/
    train_path: ptb3-wsj-train.conllx
    dev_path: ptb3-wsj-dev.conllx
    test_path: ptb3-wsj-test.conllx
  embeddings:
    type: token #{token,subword}
    root: my_tests/
    train_path: ptb3-wsj-train.bert-layers.hdf5
    dev_path: ptb3-wsj-dev.bert-layers.hdf5
    test_path: ptb3-wsj-test.bert-layers.hdf5
  batch_size: 40
model:
  hidden_dim: 1024 # BERT hidden dim
  #embedding_dim: 1024 # ELMo word embedding dim
  model_type: BERT-disk # BERT-disk, ELMo-disk, 
  use_disk: False
  model_layer: 11 # BERT-base: {1,...,12}; ELMo: {1,2,3}
probe:
  task_signature: word # word, word_pair
  task_name: parse-distance
  maximum_rank: 1024
  psd_parameters: True
  diagonal: False
  depth_params_path: example/data/bertlarge16-depth-probe.params
  distance_params_path: example/data/bertlarge16-distance-probe.params
  params_path: example/data/bertlarge16-distance-probe.params
probe_training:
  epochs: 30
  loss: L1
reporting:
  root: results/ 
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - spearmanr
      #- image_examples
    - uuas
