#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Stampede2 KNL nodes
#
#   *** Serial Job on Normal Queue ***
# 
# Last revised: 20 Oct 2017
#
# Notes:
#
#   -- Copy/edit this script as desired.  Launch by executing
#      "sbatch knl.serial.slurm" on a Stampede2 login node.
#
#   -- Serial codes run on a single node (upper case N = 1).
#        A serial code ignores the value of lower case n,
#        but slurm needs a plausible value to schedule the job.
#
#   -- For a good way to run multiple serial executables at the
#        same time, execute "module load launcher" followed
#        by "module help launcher".

#----------------------------------------------------

#SBATCH -J bert_sst # Job name
#SBATCH -o runs/first_try/output.o%j       # Name of stdout output file
#SBATCH -e runs/first_try/errors.e%j       # Name of stderr error file
#SBATCH -p gtx # Queue (partition) name
#SBATCH -N 1               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 08:30:00        # Run time (hh:mm:ss)
#SBATCH --mail-user=mli@utexas.edu
#SBATCH --mail-type=all    # Send email at begin and end of job
#SBATCH -A CS391D-Projects # Allocation name (req'd if you have more than 1)

# Other commands must follow all #SBATCH directives...

module list
pwd
date

# Launch serial code...
python finetune_bert.py --run_name first_try --epochs 25 --batch_size 12

# ---------------------------------------------------
